# Generated by Django 2.2 on 2024-04-05 23:20

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=255)),
                ('type', models.IntegerField()),
                ('active', models.BooleanField(default=True)),
                ('frequency', models.CharField(default='daily', max_length=20)),
            ],
        ),
    ]
