# Generated by Django 5.0.3 on 2024-04-08 06:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('questions', '0003_alter_answer_user_alter_questiontracker_user'),
    ]

    operations = [
        migrations.RenameField(
            model_name='likertanswer',
            old_name='answer_id',
            new_name='answer',
        ),
    ]
