# Generated by Django 2.2 on 2024-04-08 20:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('questions', '0007_auto_20240408_1831'),
    ]

    operations = [
        migrations.RenameField(
            model_name='likertanswer',
            old_name='value',
            new_name='likert_answer',
        ),
    ]
