# Generated by Django 2.2 on 2024-04-08 20:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('questions', '0008_auto_20240408_2046'),
    ]

    operations = [
        migrations.RenameField(
            model_name='likertanswer',
            old_name='likert_answer',
            new_name='likert',
        ),
    ]
