# Generated by Django 2.2 on 2024-04-09 06:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('questions', '0009_auto_20240408_2052'),
    ]

    operations = [
        migrations.AlterField(
            model_name='textanswer',
            name='text',
            field=models.CharField(max_length=100),
        ),
    ]
