# Generated by Django 5.0.3 on 2024-04-06 22:08

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('lotus', '0007_user_remove_entry_user_remove_journal_entry_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Entry',
            fields=[
                ('entry_id', models.AutoField(primary_key=True, serialize=False)),
                ('date', models.DateTimeField(default=django.utils.timezone.now)),
                ('is_journal', models.BooleanField(default=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='lotus.user')),
            ],
        ),
        migrations.CreateModel(
            name='Journal',
            fields=[
                ('journal_id', models.AutoField(primary_key=True, serialize=False)),
                ('text', models.TextField()),
                ('entry', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='journal.entry')),
            ],
        ),
        migrations.CreateModel(
            name='Memory',
            fields=[
                ('memory_id', models.AutoField(primary_key=True, serialize=False)),
                ('emotion', models.CharField(max_length=40)),
                ('text', models.CharField(max_length=60)),
                ('entry', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='journal.entry')),
            ],
        ),
    ]
