# Generated by Django 2.2 on 2024-04-06 23:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('journal', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Memory',
        ),
    ]
