# Generated by Django 2.2 on 2024-04-08 20:46

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('memories', '0003_alter_memory_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='memory',
            name='date',
            field=models.DateField(default=datetime.datetime.now),
        ),
    ]
