# Generated by Django 2.2 on 2024-03-19 05:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lotus', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='entry',
            name='user_id',
        ),
        migrations.RemoveField(
            model_name='journal',
            name='entry_id',
        ),
        migrations.RemoveField(
            model_name='likertanswer',
            name='answer_id',
        ),
        migrations.RemoveField(
            model_name='memory',
            name='entry_id',
        ),
        migrations.RemoveField(
            model_name='questiontracker',
            name='question_id',
        ),
        migrations.RemoveField(
            model_name='questiontracker',
            name='user_id',
        ),
        migrations.RemoveField(
            model_name='textanswer',
            name='answer_id',
        ),
        migrations.DeleteModel(
            name='Answer',
        ),
        migrations.DeleteModel(
            name='Entry',
        ),
        migrations.DeleteModel(
            name='Journal',
        ),
        migrations.DeleteModel(
            name='LikertAnswer',
        ),
        migrations.DeleteModel(
            name='Memory',
        ),
        migrations.DeleteModel(
            name='Question',
        ),
        migrations.DeleteModel(
            name='QuestionTracker',
        ),
        migrations.DeleteModel(
            name='TextAnswer',
        ),
        migrations.DeleteModel(
            name='User',
        ),
    ]
