# Generated by Django 2.2 on 2024-03-19 06:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('lotus', '0003_auto_20240319_0631'),
    ]

    operations = [
        migrations.AlterField(
            model_name='questiontracker',
            name='question',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='lotus.Question'),
        ),
        migrations.AlterField(
            model_name='questiontracker',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='lotus.User'),
        ),
    ]
