# Generated by Django 5.0.3 on 2024-04-04 01:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lotus', '0004_auto_20240319_0634'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='answer',
            name='question',
        ),
        migrations.RemoveField(
            model_name='answer',
            name='user',
        ),
        migrations.RemoveField(
            model_name='textanswer',
            name='answer',
        ),
        migrations.RemoveField(
            model_name='questiontracker',
            name='question',
        ),
        migrations.RemoveField(
            model_name='questiontracker',
            name='user',
        ),
        migrations.DeleteModel(
            name='LikertAnswer',
        ),
        migrations.DeleteModel(
            name='Answer',
        ),
        migrations.DeleteModel(
            name='TextAnswer',
        ),
        migrations.DeleteModel(
            name='Question',
        ),
        migrations.DeleteModel(
            name='QuestionTracker',
        ),
    ]
