# Generated by Django 5.0.3 on 2024-04-06 22:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lotus', '0006_alter_entry_user_delete_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('user_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=60)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('password', models.CharField(max_length=255)),
                ('colourscheme', models.IntegerField(default=1)),
                ('admin', models.BooleanField(default=False)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.RemoveField(
            model_name='entry',
            name='user',
        ),
        migrations.RemoveField(
            model_name='journal',
            name='entry',
        ),
        migrations.DeleteModel(
            name='Memory',
        ),
        migrations.DeleteModel(
            name='Entry',
        ),
        migrations.DeleteModel(
            name='Journal',
        ),
    ]
