# Generated by Django 5.0.3 on 2024-04-07 04:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('journal', '0003_alter_entry_user'),
        ('lotus', '0007_user_remove_entry_user_remove_journal_entry_and_more'),
        ('questions', '0003_alter_answer_user_alter_questiontracker_user'),
    ]

    operations = [
        migrations.DeleteModel(
            name='User',
        ),
    ]
